package trip.spi.inject;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.Writer;
import java.lang.annotation.Annotation;
import java.net.URI;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Map;
import java.util.Set;

import javax.annotation.processing.AbstractProcessor;
import javax.annotation.processing.Filer;
import javax.annotation.processing.RoundEnvironment;
import javax.annotation.processing.SupportedAnnotationTypes;
import javax.lang.model.SourceVersion;
import javax.lang.model.element.Element;
import javax.lang.model.element.ElementKind;
import javax.lang.model.element.ExecutableElement;
import javax.lang.model.element.TypeElement;
import javax.tools.FileObject;
import javax.tools.JavaFileObject;
import javax.tools.StandardLocation;

import trip.spi.Producer;
import trip.spi.ProviderFactory;
import trip.spi.Singleton;
import trip.spi.Stateless;
import trip.spi.helpers.cache.ServiceLoader;

import com.github.mustachejava.DefaultMustacheFactory;
import com.github.mustachejava.Mustache;

@SupportedAnnotationTypes( "trip.spi.*" )
public class ProvidedClassesProcessor extends AbstractProcessor {

	static final String EOL = "\n";
	static final String SERVICES = "META-INF/services/";
	static final String PROVIDER_FILE = SERVICES + ProviderFactory.class.getCanonicalName();

	final DefaultMustacheFactory mustacheFactory = new DefaultMustacheFactory();
	final Mustache factoryProviderClazzTemplate = this.mustacheFactory.compile( "META-INF/provided-class.mustache" );
	final Map<String, Set<String>> singletons = new HashMap<>();

	@Override
	public boolean process( final Set<? extends TypeElement> annotations, final RoundEnvironment roundEnv ) {
		try {
			process( roundEnv );
		} catch ( final IOException e ) {
			e.printStackTrace();
		}
		return true;
	}

	void process( final RoundEnvironment roundEnv ) throws IOException {
		memorizeServicesAnnotatedWith( roundEnv, Singleton.class );
		memorizeServicesAnnotatedWith( roundEnv, Stateless.class );
		processProducers( roundEnv, Stateless.class );
		processProducers( roundEnv, Producer.class );
		if ( !this.singletons.isEmpty() )
			createSingletonMetaInf();
		flush();
	}

	void memorizeServicesAnnotatedWith( final RoundEnvironment roundEnv, final Class<? extends Annotation> annotation ) {
		final Set<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith( annotation );
		for ( final Element element : annotatedElements )
			if ( element.getKind() == ElementKind.CLASS )
				memorizeASingletonImplementation( ServiceImplementation.from( element ) );
	}

	void memorizeASingletonImplementation( final ServiceImplementation from ) {
		Set<String> list = this.singletons.get( from.interfaceClass() );
		if ( list == null ) {
			list = readAListWithAllCreatedClassesImplementing( from.interfaceClass() );
			this.singletons.put( from.interfaceClass(), list );
		}
		list.add( from.implementationClass() );
	}

	private HashSet<String> readAListWithAllCreatedClassesImplementing( final String interfaceClass ) {
		final LinkedHashSet<String> singletons = new LinkedHashSet<>();
		for ( final Class<?> implementationClass : ServiceLoader.loadImplementationsFor( interfaceClass ) )
			singletons.add( implementationClass.getCanonicalName() );
		return singletons;
	}

	void processProducers( final RoundEnvironment roundEnv, final Class<? extends Annotation> annotation ) throws IOException {
		final Set<? extends Element> annotatedElements = roundEnv.getElementsAnnotatedWith( annotation );
		for ( final Element element : annotatedElements )
			if ( element.getKind() == ElementKind.METHOD )
				createAProducerFrom( ProducerImplementation.from( (ExecutableElement)element ) );
			else if ( element.getKind() == ElementKind.CLASS )
				createAProducerFrom( ProducerImplementation.from( (TypeElement)element ) );
	}

	void createAProducerFrom( final ProducerImplementation clazz ) throws IOException {
		final String name = createClassCanonicalName( clazz );
		if ( !classExists( clazz, name ) ) {
			System.out.println( "Generating " + name );
			final JavaFileObject sourceFile = filer().createSourceFile( name );
			final Writer writer = sourceFile.openWriter();
			this.factoryProviderClazzTemplate.execute( writer, clazz );
			writer.close();
		}
	}

	boolean classExists( final ProducerImplementation clazz, final String name ) {
		try {
			Class.forName( name );
			return true;
		} catch ( IllegalArgumentException | ClassNotFoundException cause ) {
			return false;
		}
	}

	String createClassCanonicalName( final ProducerImplementation clazz ) {
		return String.format( "%s.%sAutoGeneratedProvider%s",
				clazz.packageName(),
				clazz.typeName(),
				clazz.providerName() );
	}

	void createSingletonMetaInf() throws IOException {
		for ( final String interfaceClass : this.singletons.keySet() ) {
			System.out.println( "Registering service providers for " + interfaceClass );
			final Writer resource = createResource( SERVICES + interfaceClass );
			for ( final String implementation : this.singletons.get( interfaceClass ) )
				resource.write( implementation + EOL );
			resource.close();
		}
	}

	Writer createResource( final String resourcePath ) throws IOException {
		final FileObject resource = filer().getResource( StandardLocation.CLASS_OUTPUT, "", resourcePath );
		final URI uri = resource.toUri();
		createNeededDirectoriesTo( uri );
		final File file = createFile( uri );
		return new FileWriter( file );
	}

	void createNeededDirectoriesTo( final URI uri ) {
		File dir = null;
		if ( uri.isAbsolute() )
			dir = new File( uri ).getParentFile();
		else
			dir = new File( uri.toString() ).getParentFile();
		dir.mkdirs();
	}

	File createFile( final URI uri ) throws IOException {
		final File file = new File( uri );
		if ( !file.exists() )
			file.createNewFile();
		return file;
	}

	Filer filer() {
		return this.processingEnv.getFiler();
	}

	void flush() {
		this.singletons.clear();
	}

	/**
	 * We just return the latest version of whatever JDK we run on. Stupid?
	 * Yeah, but it's either that or warnings on all versions but 1. Blame Joe.
	 * 
	 * PS: this method was copied from Project Lombok. ;)
	 */
	@Override
	public SourceVersion getSupportedSourceVersion() {
		return SourceVersion.values()[SourceVersion.values().length - 1];
	}
}
